# Generated by Django 6.0.6 on 2026-06-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('technician', 'Technician'), ('pathologist', 'Pathologist')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('entered', 'Entered'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_entered', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_report', to='api.registration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range_male', models.CharField(blank=True, max_length=100)),
                ('reference_range_female', models.CharField(blank=True, max_length=100)),
                ('reference_range_child', models.CharField(blank=True, max_length=100)),
                ('critical_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('critical_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.test')),
            ],
            options={
                'ordering': ['test__name', 'parameter_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('flag', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.report')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_values', to='api.testparameter')),
            ],
        ),
        migrations.AddIndex(
            model_name='testparameter',
            index=models.Index(fields=['test', 'is_active'], name='api_testpar_test_id_b2fc35_idx'),
        ),
        migrations.AddConstraint(
            model_name='testparameter',
            constraint=models.UniqueConstraint(fields=('test', 'parameter_name'), name='unique_parameter_per_test'),
        ),
        migrations.AddConstraint(
            model_name='reportvalue',
            constraint=models.UniqueConstraint(fields=('report', 'parameter'), name='unique_value_per_parameter'),
        ),
    ]
