# Generated by Django 6.0.7 on 2026-07-21 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_test_mrp_sample_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSampleBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sample_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_sample_barcodes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_barcodes', to='api.patient')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_barcodes', to='api.registration')),
            ],
            options={
                'ordering': ['-linked_at'],
                'indexes': [
                    models.Index(fields=['patient', 'sample_type'], name='api_patient_patient_6d0f8d_idx'),
                    models.Index(fields=['registration', 'sample_type'], name='api_patient_registr_0d4b2a_idx'),
                ],
            },
        ),
    ]
