# Generated by Django 6.0.7 on 2026-07-31 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_franchise_role_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseCommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_franchise_pct', models.DecimalField(decimal_places=2, default=5, help_text='Commission % credited to Sub-Franchise when they (or their booking) generate revenue.', max_digits=5)),
                ('franchisee_pct', models.DecimalField(decimal_places=2, default=3, help_text='Commission % credited to Prime in the hierarchy.', max_digits=5)),
                ('super_franchisee_pct', models.DecimalField(decimal_places=2, default=2, help_text='Commission % credited to Supreme in the hierarchy.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Franchise commission config',
            },
        ),
        migrations.CreateModel(
            name='FranchiseWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Franchise wallet',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('commission', 'Commission'), ('top_up', 'Top-up'), ('debit', 'Debit'), ('adjustment', 'Adjustment'), ('demo', 'Demo')], max_length=20)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_rate_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Registration net_amount (or demo base) used to compute commission.', max_digits=14, null=True)),
                ('beneficiary_role', models.CharField(blank=True, max_length=30)),
                ('batch_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='patientsamplebarcode',
            new_name='api_patient_patient_1bda0d_idx',
            old_name='api_patient_patient_6d0f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='patientsamplebarcode',
            new_name='api_patient_registr_10a156_idx',
            old_name='api_patient_registr_0d4b2a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('hr', 'HR'), ('pathologist', 'Pathologist'), ('technician', 'Technician'), ('receptionist', 'Receptionist'), ('super_franchisee', 'Supreme'), ('franchisee', 'Prime'), ('sub_franchise', 'Sub-Franchise')], default='user', max_length=30),
        ),
        migrations.AddField(
            model_name='franchisewallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='api.registration'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source_user',
            field=models.ForeignKey(blank=True, help_text='User whose booking/activity generated this credit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions_sourced', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.franchisewallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['txn_type', 'created_at'], name='api_wallett_txn_typ_71a604_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['batch_key'], name='api_wallett_batch_k_6e8cc0_idx'),
        ),
    ]
