# Generated by Django 6.0.7 on 2026-08-09 13:53

from decimal import Decimal

from django.db import migrations, models


def seed_test_section(apps, schema_editor):
    Test = apps.get_model('api', 'Test')
    TestPackage = apps.get_model('api', 'TestPackage')
    ReportFormatAsset = apps.get_model('api', 'ReportFormatAsset')

    for test in Test.objects.all()[:500]:
        updates = []
        if not test.tat:
            test.tat = '24 hrs'
            updates.append('tat')
        if not test.volume_ml:
            name = (test.name or '').upper()
            sample = (test.sample_type or '').upper()
            if 'URINE' in sample or 'URINE' in name:
                test.volume_ml = Decimal('10.00')
            elif 'EDTA' in sample or 'CBC' in name:
                test.volume_ml = Decimal('2.00')
            else:
                test.volume_ml = Decimal('3.00')
            updates.append('volume_ml')
        if updates:
            test.save(update_fields=updates)

    package_defs = [
        ('1.3 Fitness Advance', ['CBC', 'Lipid', 'LFT', 'KFT', 'Sugar', 'Glucose']),
        ('ADVANCE full body check', ['CBC', 'Thyroid', 'Vitamin', 'HbA1c', 'Urine']),
        ('ALLERGY PANEL II', ['Allergy', 'IgE', 'Eosinophil']),
    ]
    for index, (pkg_name, keywords) in enumerate(package_defs):
        pkg, _ = TestPackage.objects.get_or_create(
            name=pkg_name,
            defaults={'description': 'Combo / package tests', 'sort_order': index},
        )
        matched = []
        for test in Test.objects.all():
            upper = (test.name or '').upper()
            if any(key.upper() in upper for key in keywords):
                matched.append(test)
            if len(matched) >= 6:
                break
        if matched:
            pkg.tests.set(matched[:6])

    demos = [
        ('CBC Sample Report (Demo)', 'image', 'Demo CBC report layout for franchise preview.'),
        ('Full Body Package Report (Demo)', 'pdf', 'Sample package report PDF placeholder.'),
        ('Pathology Report Format (Demo)', 'image', 'Demo pathology report image format.'),
    ]
    for index, (title, file_type, description) in enumerate(demos):
        ReportFormatAsset.objects.get_or_create(
            title=title,
            defaults={
                'description': description,
                'file_type': file_type,
                'is_demo': True,
                'is_active': True,
                'sort_order': index,
                'external_url': '',
            },
        )


def unseed_test_section(apps, schema_editor):
    TestPackage = apps.get_model('api', 'TestPackage')
    ReportFormatAsset = apps.get_model('api', 'ReportFormatAsset')
    TestPackage.objects.filter(name__in=[
        '1.3 Fitness Advance',
        'ADVANCE full body check',
        'ALLERGY PANEL II',
    ]).delete()
    ReportFormatAsset.objects.filter(is_demo=True, title__icontains='Demo').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_franchise_ledger_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFormatAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='report-formats/')),
                ('external_url', models.URLField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='pdf', max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report format asset',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='tat',
            field=models.CharField(blank=True, help_text='Turnaround time to release report (e.g. 24 hrs).', max_length=80),
        ),
        migrations.AddField(
            model_name='test',
            name='volume_ml',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sample volume in ml.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='test',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Patient MRP.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='B2B / franchise rate.', max_digits=10),
        ),
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tests', models.ManyToManyField(blank=True, related_name='packages', to='api.test')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_test_section, unseed_test_section),
    ]
