#!/bin/sh
# Configure backend/.env for PostgreSQL and run migrations.
# Usage:
#   ./setup_postgres.sh
#   ./setup_postgres.sh "postgresql://user:pass@host:port/dbname"

set -e
cd "$(dirname "$0")"

if [ -f venv/bin/activate ]; then
  # shellcheck disable=SC1091
  . venv/bin/activate
fi

DEFAULT_LOCAL_URL="postgresql://clasmo:clasmo@127.0.0.1:5432/clasmo"

if [ -n "$1" ]; then
  DB_URL="$1"
else
  echo "Paste your PostgreSQL connection URL."
  echo "Press Enter to use local Docker Postgres (${DEFAULT_LOCAL_URL})"
  printf "> "
  read -r DB_URL
  if [ -z "$DB_URL" ]; then
    DB_URL="$DEFAULT_LOCAL_URL"
  fi
fi

SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"

cat > .env <<EOF
# Generated by setup_postgres.sh — do not commit
SECRET_KEY=${SECRET_KEY}
DEBUG=true

DATABASE_PUBLIC_URL=${DB_URL}
DATABASE_URL=${DB_URL}
EOF

echo "Wrote backend/.env"
echo "Database URL host: $(python3 -c "from urllib.parse import urlparse; print(urlparse('${DB_URL}').hostname or 'unknown')")"

if ! python3 -c "import django" 2>/dev/null; then
  echo "Activate venv first: source venv/bin/activate"
  exit 1
fi

python3 -c "
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'clasmo_backend.settings')
import django
django.setup()
from django.conf import settings
db = settings.DATABASES['default']
print('Engine:', db['ENGINE'])
print('Host:', db.get('HOST'))
print('Name:', db.get('NAME'))
"

echo "Running migrations..."
python3 manage.py migrate --noinput
echo "Seeding trial users and sample data..."
python3 manage.py seed_data || true
python3 manage.py seed_clinical_data || true
echo "Done. Start backend with: python manage.py runserver"
