export const ROLE_PERMISSION_SCHEMA = [
  { key: 'search', label: 'Search' },
  { key: 'registration', label: 'Test Registration' },
  { key: 'test_result', label: 'Test Result' },
  { key: 'administration', label: 'Administration' },
  { key: 'reports', label: 'Reports' },
  { key: 'device_request', label: 'Device Request' },
  { key: 'dashboard', label: 'Dashboard' },
  { key: 'elab_pay', label: 'Elab-PAY' },
  { key: 'help', label: 'Help' },
  { key: 'result_entry', label: 'Result Entry' },
  { key: 'report_preview', label: 'Report Preview' },
  { key: 'test_parameters', label: 'Test Parameter Master' },
  { key: 'manage_users', label: 'Manage Users' },
  { key: 'manage_roles', label: 'Manage Roles' },
];
